### ISSUE TITLE
AnnualDate

### ISSUE THREAD

**Issue by Nosferican** [matthieugomez/MonthlyDates.jl#12]
Would it be possible to provide a similar type for annual data (`AnnualDate`)?

**Comment by matthieugomez** [comment]
Can you give me examples for why it is better than just Integers?

**Comment by Nosferican** [comment]
I am writing a client for the [BEA API ](https://apps.bea.gov/api/_pdf/bea_web_service_api_user_guide.pdf). The available frequencies are annual, quarterly, and monthly (depending on the dataset/table). I am thinking that it would be easier to have all three frequencies support the datetime API / being understood as a `DateTime`. I don't have specific instances of concrete benefits yet other than having the time period column being `Vector{TimeType}` rather than materializing as `Vector{Any}` and then converting it to `Vector{Union{Int64, QuarterlyDate, MonthlyDate}}`. It might also play nicer for plotting as well.

**Comment by matthieugomez** [comment]
Added with https://github.com/matthieugomez/MonthlyDates.jl/commit/89a790439adca8ea731159da0ba338508d3d9129
Let me know if you find missing operations
