### ISSUE TITLE
Strange behavior when year is Float versus Int

### ISSUE THREAD

**Issue by eloualiche** [matthieugomez/MonthlyDates.jl#2]
MonthlyDates gives inconsistent results when the first argument is a Float rather than an Int. 

```julia
> x = 192607
> MonthlyDate(floor(x / 100), x % 100)
1927q3
> MonthlyDate(Int(floor(x / 100)), x % 100)
1926m7
```

Maybe I am missing something and this is a feature that is useful somewhere else?

**Comment by matthieugomez** [comment]
That was a bug. Just corrected it, thanks!
