### ISSUE TITLE
Writing to CSV

### ISSUE THREAD

**Issue by eloualiche** [matthieugomez/MonthlyDates.jl#3]
I am trying to save a dataset with monthly dates. It seems that I am not able to at this stage. 

It seems that everything is ok for Dates:
```julia
using DataFrames, MonthlyDates, Dates
using CSV
df = DataFrame(x = DateTime(1983, 12, 1), y = "a", z=1)
CSV.write("test.csv", df)
```

Monthly dates would probably have to be translated into dates?
```julia
df = DataFrame(x = MonthlyDate(1983, 12), y = "a", z=1)
CSV.write("test.csv", df)
```

Probably would make sense to crosspost on [CSV.jl](https://github.com/JuliaData/CSV.jl/issues)

**Comment by matthieugomez** [comment]
Done with the last commit. Thanks!
