### ISSUE TITLE
Safeguard against invalid month/quarter values

### ISSUE THREAD

**Issue by FuZhiyu** [matthieugomez/MonthlyDates.jl#6]
When we try to construct a `Date` with invalid months/days, an `ArgumentError` will be thrown
```
julia> Date(1991, 12, 45)
ERROR: ArgumentError: Day: 45 out of range (1:31)
```

They have a `validargs` function checking whether the arguments are out of range. This mechanism is missing in this package, so if we pass year-month to `QuarterlyDate`, it won't complain but roll it over to the next year:

```
julia> QuarterlyDate(1995, 5)
1996-Q1
```

It seems pretty error-prone to me. I once passed year-month pairs to `QuarterlyDate` and screwed up the whole dataset. Do you think we should also implement a `validargs` function here to avoid invalid arguments?

I could work on it if you also like this idea.

**Comment by matthieugomez** [comment]
Absolutely! We should check arguments are valid.
